const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const TerserPlugin = require('terser-webpack-plugin');

const isDev = process.env.NODE_ENV !== 'production';

module.exports = {
  mode: isDev ? 'development' : 'production',
  devtool: isDev ? 'inline-source-map' : false,
  
  entry: {
    // Extension pages
    popup: './src/popup/index.tsx',
    options: './src/options/index.tsx',
    
    // Background script
    background: './src/background/service-worker.ts',
    
    // Content script
    content: './src/content/content.ts',
  },
  
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: '[name].js',
    clean: true,
  },
  
  module: {
    rules: [
      // TypeScript and TSX files
      {
        test: /\.tsx?$/,
        use: [
          {
            loader: 'ts-loader',
            options: {
              transpileOnly: true,
              compilerOptions: {
                jsx: 'react-jsx',
              },
            },
          },
        ],
        exclude: /node_modules/,
      },
      
      // CSS files
      {
        test: /\.css$/,
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader',
          'postcss-loader',
        ],
      },
      
      // Images and fonts
      {
        test: /\.(png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$/,
        type: 'asset/resource',
        generator: {
          filename: 'assets/[name][ext]',
        },
      },
    ],
  },
  
  resolve: {
    extensions: ['.tsx', '.ts', '.jsx', '.js'],
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
  },
  
  plugins: [
    // Clean dist folder before build
    new CleanWebpackPlugin(),
    
    // Extract CSS into separate files
    new MiniCssExtractPlugin({
      filename: 'assets/[name].css',
    }),
    
    // Define environment variables
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(isDev ? 'development' : 'production'),
    }),
    
    // Generate popup.html
    new HtmlWebpackPlugin({
      template: './src/popup/index.html',
      filename: 'popup.html',
      chunks: ['popup'],
      inject: 'body',
      minify: !isDev,
      scriptLoading: 'module',
      meta: {
        viewport: 'width=device-width, initial-scale=1.0',
      },
      // Custom template parameters
      templateParameters: {
        isDev,
      },
    }),
    
    // Generate options.html
    new HtmlWebpackPlugin({
      template: './src/options/index.html',
      filename: 'options.html',
      chunks: ['options'],
      inject: 'body',
      minify: !isDev,
      scriptLoading: 'module',
      meta: {
        viewport: 'width=device-width, initial-scale=1.0',
      },
      templateParameters: {
        isDev,
      },
    }),
    
    // Copy static files
    new CopyWebpackPlugin({
      patterns: [
        // Copy manifest.json
        {
          from: 'public/manifest.json',
          to: 'manifest.json',
        },
        
        // Copy icons
        {
          from: 'public/icons',
          to: 'icons',
        },
        
        // Copy rules
        {
          from: 'public/rules',
          to: 'rules',
        },
        
        // Copy locales
        {
          from: 'public/_locales',
          to: '_locales',
        },
        
        // Copy theme-loader.js
        {
          from: 'public/theme-loader.js',
          to: 'theme-loader.js',
        },
        
        // Copy content.css
        {
          from: 'public/content.css',
          to: 'content.css',
        },
        
        // Copy other HTML files (excluding those generated by HtmlWebpackPlugin)
        {
          from: 'public/*.html',
          to: '[name][ext]',
          globOptions: {
            ignore: ['**/popup.html', '**/options.html'],
          },
        },
      ],
    }),
  ],
  
  optimization: {
    minimize: !isDev,
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          compress: {
            drop_console: !isDev,
            drop_debugger: !isDev,
          },
          mangle: true,
        },
      }),
    ],
    
    splitChunks: {
      chunks: 'async',
      cacheGroups: {
        vendor: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendor',
          chunks: 'all',
          priority: 10,
        },
        common: {
          minChunks: 2,
          priority: 5,
          reuseExistingChunk: true,
        },
      },
    },
  },
  
  // Chrome extension specific settings
  target: 'web',
  
  performance: {
    hints: false,
    maxEntrypointSize: 512000,
    maxAssetSize: 512000,
  },
  
  // Development server config (for testing)
  devServer: {
    static: {
      directory: path.join(__dirname, 'dist'),
    },
    compress: true,
    port: 9000,
    hot: false,
    liveReload: false,
    devMiddleware: {
      writeToDisk: true,
    },
  },
  
  // Watch options
  watchOptions: {
    ignored: /node_modules/,
    aggregateTimeout: 300,
    poll: 1000,
  },
};